### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by lia789** [Arinze1020/Auto#1]
Hy! Your tutorial was just nice. Buy some site give some errors like "callback is not a function".
How can I solve this any idea?

**Comment by Arinze1020** [comment]
You have to get the callback function, yes must of the site always say so
at first you might not see the callback but if you keep looking you will
find it

**Comment by lia789** [comment]
Thanks! It works now...
Your tutorial was awsam.

**Comment by Arinze1020** [comment]
Awesome, thanks!, am glad it helped you
